name: life_wasted
description: Wasted life week calculator

version: 1.0.0+2

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.0.7+5
  intl: ^0.17.0
  provider: ^6.0.3
  flutter_mobx: ^2.0.6+1
  google_fonts: ^3.0.1
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.0.15
  font_awesome_flutter: ^10.2.1

dev_dependencies:
  analyzer: ^4.7.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  mobx_codegen: ^2.0.4
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
