name: life_wasted
description: Wasted life week calculator

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.7.0
  shared_preferences: ^0.5.6+3
  provider: ^4.0.4
  mobx: 1.0.2+2
  flutter_mobx: ^1.0.1
  floating_action_row: ^0.1.0
  cupertino_icons: ^0.1.2
  esys_flutter_share: ^1.0.2
  google_fonts: ^0.3.10
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.0
  mobx_codegen: ^1.0.2
  flutter_launcher_icons: ^0.7.4

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
